DROP TABLE IF EXISTS folders;
DROP TABLE IF EXISTS notes;
CREATE TABLE folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
 );

CREATE TABLE notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    content TEXT,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    folderId INTEGER REFERENCES folders(id) ON DELETE CASCADE
);

INSERT INTO folders (name) VALUES (
    'Test Folder 1'
),
(
    'Test Folder 2'
),
(
    'Test Folder 3'
);

INSERT INTO notes (name, content, folderId)
VALUES ('Note Title 1', 'Note Content 1', 1),
('Note Title 2', 'Note Content 2', 2),
('Note Title 3', 'Note Content 3', 3);