
CREATE TABLE notes(
    id INTEGER PRIMARY KEY GENERATE BY DEFAULT AS IDENTITY,
    note_title TEXT NOT NULL,
    note_content TEXT ,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    folder_id INTEGER REFERENCES folder(id) ON DELETE CASCADE
);